email tst

diff --git a/.github/workflows/text-email.yaml b/.github/workflows/text-email.yaml
--- a/.github/workflows/text-email.yaml
+++ b/.github/workflows/text-email.yaml
@@ -47,13 +47,21 @@ jobs:
       -   name: get content
           id: get-content
           run: |
-              url="${{ env.BASE_URL }}/issue-${{ env.ISSUE_NO }}/"
+              url="https://roundup.stlgame.dev/issue-${{ env.ISSUE_NO }}/"
               div_id="content"
               ru_content=$(curl -s $url | grep -A 1 "<div id=\"$div_id\">" | tail -n 1)
+
+              if [ -z "$ru_content" ]; then
+                echo "Error: Failed to extract content from the URL $url"
+                exit 1
+              fi
+
               email_template=".github/workflows/email-template.html"
               email_content=$(cat $email_template)
+
               content=$(echo $email_content | sed "s/\*|ISSUE_NO|\*/${{ env.ISSUE_NO }}/g")
               content=$(echo $content | sed "s/\*|CONTENT|\*/$ru_content/g")
+
               echo "content=$content" >> $GITHUB_ENV
           env:
             MAILCHIMP_DC: ${{ secrets.MAILCHIMP_DC }}
